language: node_js
node_js: '10'
notifications:
  email: false
deploy:
  provider: heroku
  api_key:
    secure: ncD1o2bmvVmkjiLGdC2+Mnfq+fnUQyccPQhFTzCTfQjJsSythjmN+SwEzpyzOCdAa94npKF7RgD0YoxsWQW8FWhH1tcR8ZivtwmRiScrVwThkNM5l6WvZf4bo4lKOvmel5+OYJYVyqkzEbzLZS0n0pILcW5nfn+lD9eaBgo3spViihVi/HoR1jlFXexr+6rt4w4XhK7iwYsBKXZ0e2+3VsbD8+5vQ4klXpY0pVgyJow/yohiHuuardNZOwlplH0IFrMEEDmgK6Nz1w4VbiUrtNQj/DqKn6JyOQjq3+et/sthokYNILegimNg/Iw11LOvMUXNVSlKHrYnERR5pp8d8myce9g5u03SXEveQHUJyj2/Jc+cKw73L8XKxGJyaKOeeKBhqn5V/zmcpREW5iOOBetEOydac66Ly2VRlBHMDLptae7vZM5R+R5L5EeDDZfSS97w3kei7ielDFkl8Ev6AdpO2KsehMU2pwD2qqMEPbC6M+3c5jxNbjzna1IYKYuAIIE3j43hBuRhoAHwA3MaO5nA28nEnWgyNTDx4wBJX/48LtFCMEu/T4V4GlMj0KeDpAZ7ZwT/XkHA8hCFJxJ2R6IFkCVnurwKsuSVK15YOUvZL5YDXYe4gWJeXmREzETHTGKwAI6i85w8gDJrqOMDmYGWwOQsHKAK5MuZOdkLq1o=
  app: game-tyme
  skip_cleanup: true
  on:
    repo: hmmChase/game-time
